/*
    Problem 2
    Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
let topla = 0;
let a = 1;
let b = 2;
for (let i = 0; b < 4000000; i++) {
  if (b % 2 === 0) {
    topla += b;
  }
  let fibonacci = a + b;
  a = b;
  b = fibonacci;
}
console.log("Toplam Fibonacci:", topla); //Toplam Fibonacci: 4613732
